import matplotlib.pyplot as plt

entree = "NNEESOONNEESOOESEENNEEOOSEOSEEENNESENSSENNEESSOOEEENNEEOOSEOSEEENEENOOEESOOSEEEEEEENONSESENNSSENNEESSOOEEENNSSEENNSSEEENOONEEOOSEESEEEENNEESSOOEEENNEESOOEESENNESENSSEEENOONEEOOSEESEEEENNSSEEENNEESOOEESEEEENNEEOOSEOSEEENNEESSOOEEENNEESOOESEENNEEOOSEOSEEEENNOEEOSSEEEEENNEESOOEESOOEEENNEESOOESEENNSSEENNSSENNESNESSENNEEOOSEOSEEENNSSEENNSSEEENOONEEOOSEESENNEEOOSEOSEEEEEENNEESSOOEEENNEEOOSEOSEEENNESNESSENNEESOOEESENNSSENNESENSSEES"  # <-- colle ici la séquence
moves = {'N': (0,1), 'S': (0,-1), 'E': (1,0), 'O': (-1,0)}

x = y = 0
xs, ys = [x], [y]
for c in entree:
    dx, dy = moves[c]
    x += dx; y += dy
    xs.append(x); ys.append(y)


plt.figure(figsize=(8,8))
plt.plot(xs, ys, linewidth=2)
plt.scatter(xs[0], ys[0], s=30)
plt.gca().set_aspect('equal', adjustable='box')
plt.grid(True)
plt.show()
